# Generated by Django 6.1.2 on 2026-10-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='area_place',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
